server:
  port: ${SERVER_PORT:8080}
spring:
  main:
    banner-mode: "off"
ml:
  service-url: ${ML_SERVICE_URL:http://ml-service:8000}
  client:
    connect-timeout-ms: ${ML_CLIENT_CONNECT_TIMEOUT_MS:2000}
    read-timeout-ms: ${ML_CLIENT_READ_TIMEOUT_MS:2000}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
